services:
  app:
    build: .
    container_name: farmily-app
    ports:
      - "8000:8000"
    environment:
      - LOCAL_DB=${LOCAL_DB:-false}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-family}
    restart: always
